# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ExampleOthers::InnerKlass`.
# Please instead update this file by running `bin/tapioca dsl ExampleOthers::InnerKlass`.

class ExampleOthers::InnerKlass
  sig { returns(::String) }
  def string; end
end
