# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ExampleTest`.
# Please instead update this file by running `bin/tapioca dsl ExampleTest`.

class ExampleTest
  sig { returns(::String) }
  def enum01; end

  sig { returns(::String) }
  def enum02; end

  sig { returns(::String) }
  def enum03; end

  sig { returns(::Integer) }
  def enum04; end

  sig { returns(::Integer) }
  def enum05; end

  sig { returns(::Integer) }
  def enum06; end

  sig { returns(::T.nilable(::String)) }
  def enum07; end

  sig { returns(::T.nilable(::String)) }
  def enum08; end

  sig { returns(::T.nilable(::String)) }
  def enum09; end

  sig { returns(::T.nilable(::Integer)) }
  def enum10; end

  sig { returns(::T.nilable(::Integer)) }
  def enum11; end

  sig { returns(::T.nilable(::Integer)) }
  def enum12; end
end
