# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ExampleArray::InnerKlass`.
# Please instead update this file by running `bin/tapioca dsl ExampleArray::InnerKlass`.

class ExampleArray::InnerKlass
  sig { returns(::String) }
  def string; end
end
