# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Example::Fooo`.
# Please instead update this file by running `bin/tapioca dsl Example::Fooo`.

class Example::Fooo; end
