# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ExampleNested::Fooo`.
# Please instead update this file by running `bin/tapioca dsl ExampleNested::Fooo`.

class ExampleNested::Fooo
  sig { returns(::String) }
  def string; end
end
