# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ExampleSum::InnerKlass`.
# Please instead update this file by running `bin/tapioca dsl ExampleSum::InnerKlass`.

class ExampleSum::InnerKlass
  sig { returns(::String) }
  def string; end
end
